language: bash

notifications:
    email: false

script:
    # Check if all files are formatted according to the standard
    - find . -type f -maxdepth 1 -not -name .git -exec python tests/format.py {} \;
